"""
storage.py — Where complaint photos are kept.

Photos are OPTIONAL. A complaint is a Firestore document and works completely
without one; the photo is only an extra file. The complaint document stores just
the generated file name in `image_path` (for example "3f2a...c9.png"), never the
image bytes, and that name is the same whatever keeps the file.

Which backend keeps the files is chosen with COMPLAINT_IMAGE_STORAGE (config.py):

    local   the uploads/complaints/ folder of this computer. Used for local
            development and demos. The folder is git-ignored.
    none    photo uploads are switched off; complaints are submitted without one.
            This is the default on Vercel, whose disk is temporary: a file saved
            there would disappear, so we do not pretend it is kept.

Firebase Cloud Storage is NOT used (it needs the paid Blaze plan). To add a proper
cloud image service later, write one more class with the same four methods as
LocalFolderStorage and register it in BACKENDS. Nothing else changes: routes and
helpers only call the module functions at the bottom of this file.

Privacy: photos are never in a public folder. The browser asks HostelHub's
/complaints/<id>/image route, which checks that the viewer is the student who
reported the complaint or a warden, and only then reads the photo with read_file().
"""

import os

from flask import current_app


class StorageError(Exception):
    """The photo could not be stored or read."""


def is_safe_name(filename):
    """Stored names are generated by us (uuid + extension). Reject anything else,
    such as '../app.py', before touching any storage."""
    return bool(filename) and os.path.basename(filename) == filename and not filename.startswith(".")


class LocalFolderStorage:
    """Photos as files in one folder (UPLOAD_FOLDER)."""

    enabled = True

    def __init__(self, folder):
        self.folder = folder

    def path(self, filename):
        return os.path.join(self.folder, filename)

    def save(self, filename, data, content_type):
        try:
            os.makedirs(self.folder, exist_ok=True)
            with open(self.path(filename), "wb") as file:
                file.write(data)
        except OSError as error:
            raise StorageError("The photo could not be stored.") from error

    def read(self, filename):
        try:
            with open(self.path(filename), "rb") as file:
                return file.read()
        except OSError:
            return None

    def delete(self, filename):
        try:
            os.remove(self.path(filename))
        except OSError:
            pass

    def exists(self, filename):
        return os.path.isfile(self.path(filename))


class NoImageStorage:
    """Photo uploads switched off: nothing is stored and nothing can be read."""

    enabled = False

    def save(self, filename, data, content_type):
        raise StorageError("Photo uploads are not available on this server.")

    def read(self, filename):
        return None

    def delete(self, filename):
        pass

    def exists(self, filename):
        return False


BACKENDS = {
    "local": lambda config: LocalFolderStorage(config["UPLOAD_FOLDER"]),
    "none": lambda config: NoImageStorage(),
}


def backend():
    """The photo backend chosen in the settings."""
    name = current_app.config.get("COMPLAINT_IMAGE_STORAGE", "none")
    return BACKENDS.get(name, BACKENDS["none"])(current_app.config)


# ------------------------------------------------------------------
# The operations used by helpers.py and routes/complaints.py
# ------------------------------------------------------------------

def images_enabled():
    """Can students attach a photo on this server?"""
    return backend().enabled


def save_file(filename, data, content_type):
    """Store the photo bytes under `filename`. Raises StorageError on failure."""
    if not is_safe_name(filename):
        raise StorageError("Invalid file name.")
    try:
        backend().save(filename, data, content_type)
    except StorageError as error:
        current_app.logger.warning("Could not store complaint photo: %s", error)
        raise


def read_file(filename):
    """Return the photo bytes, or None if the photo does not exist here."""
    if not is_safe_name(filename):
        return None
    return backend().read(filename)


def delete_file(filename):
    """Delete a stored photo. Missing photos are ignored."""
    if is_safe_name(filename):
        backend().delete(filename)


def file_exists(filename):
    """Can the detail page show this photo? (False if it is kept somewhere else,
    for example a photo uploaded on a laptop and viewed on the deployed site.)"""
    return is_safe_name(filename) and backend().exists(filename)
