"""
storage.py — Where complaint photos are kept.

Two storage places, chosen by configuration:

    SUPABASE_URL not set  ->  local folder uploads/complaints/   (development, tests)
    SUPABASE_URL set      ->  a PRIVATE Supabase Storage bucket  (deployment on Vercel)

Why not just a folder on Vercel? Each Vercel function gets a temporary file
system, so a photo saved there would disappear. Object storage keeps it.

Privacy is the same in both modes:
  - the bucket is private, and only the server knows the secret key
  - the browser never receives a storage link; it asks HostelHub's
    /complaints/<id>/image route, which checks the user first and then
    reads the photo through read_file() below.

Supabase Storage is used through its HTTP API with Python's built-in
urllib, so no extra package is needed:

    POST   /storage/v1/object/<bucket>/<file>                 upload
    GET    /storage/v1/object/authenticated/<bucket>/<file>   download (private)
    DELETE /storage/v1/object/<bucket>/<file>                 delete
"""

import os
import urllib.error
import urllib.request

from flask import current_app


class StorageError(Exception):
    """The photo could not be saved (for example, the storage service is unreachable)."""


def is_safe_name(filename):
    """Stored names are generated by us (uuid + extension). Reject anything else,
    such as '../app.py', before touching the disk or the network."""
    return bool(filename) and os.path.basename(filename) == filename and not filename.startswith(".")


def using_supabase():
    return bool(current_app.config["SUPABASE_URL"])


# ------------------------------------------------------------------
# Supabase helper
# ------------------------------------------------------------------

def supabase_request(method, path, data=None, content_type=None):
    """Send one request to the Supabase Storage API and return the response body."""
    settings = current_app.config
    url = f"{settings['SUPABASE_URL'].rstrip('/')}/storage/v1/object/{path}"
    key = settings["SUPABASE_SECRET_KEY"]
    headers = {"apikey": key, "Authorization": f"Bearer {key}"}
    if content_type:
        headers["Content-Type"] = content_type
    request = urllib.request.Request(url, data=data, method=method, headers=headers)
    try:
        with urllib.request.urlopen(request, timeout=15) as response:
            return response.read()
    except urllib.error.HTTPError as error:
        # A 4xx/5xx reply (wrong key, missing photo...). Close it, then let the caller handle it.
        error.close()
        raise


# ------------------------------------------------------------------
# The three operations used by helpers.py and routes/complaints.py
# ------------------------------------------------------------------

def save_file(filename, data, content_type):
    """Store the photo bytes under `filename`. Raises StorageError on failure."""
    if not is_safe_name(filename):
        raise StorageError("Invalid file name.")
    try:
        if using_supabase():
            bucket = current_app.config["SUPABASE_BUCKET"]
            supabase_request("POST", f"{bucket}/{filename}", data=data, content_type=content_type)
        else:
            folder = current_app.config["UPLOAD_FOLDER"]
            os.makedirs(folder, exist_ok=True)
            with open(os.path.join(folder, filename), "wb") as photo:
                photo.write(data)
    except (OSError, urllib.error.URLError) as error:   # HTTPError is a kind of URLError
        current_app.logger.error("Could not store complaint photo: %s", error)
        raise StorageError("The photo could not be stored.") from error


def read_file(filename):
    """Return the photo bytes, or None if the photo does not exist or cannot be read."""
    if not is_safe_name(filename):
        return None
    try:
        if using_supabase():
            bucket = current_app.config["SUPABASE_BUCKET"]
            return supabase_request("GET", f"authenticated/{bucket}/{filename}")
        path = os.path.join(current_app.config["UPLOAD_FOLDER"], filename)
        if not os.path.isfile(path):
            return None
        with open(path, "rb") as photo:
            return photo.read()
    except (OSError, urllib.error.URLError) as error:
        current_app.logger.warning("Could not read complaint photo %s: %s", filename, error)
        return None


def delete_file(filename):
    """Delete a stored photo. Missing photos are ignored."""
    if not is_safe_name(filename):
        return
    try:
        if using_supabase():
            bucket = current_app.config["SUPABASE_BUCKET"]
            supabase_request("DELETE", f"{bucket}/{filename}")
        else:
            path = os.path.join(current_app.config["UPLOAD_FOLDER"], filename)
            if os.path.isfile(path):
                os.remove(path)
    except (OSError, urllib.error.URLError) as error:
        current_app.logger.warning("Could not delete complaint photo %s: %s", filename, error)


def file_exists(filename):
    """Can the detail page show this photo?

    Locally we can check the disk cheaply. For Supabase we avoid an extra network
    call on every page view: we assume it exists, and the image route returns 404
    if it does not.
    """
    if not is_safe_name(filename):
        return False
    if using_supabase():
        return True
    return os.path.isfile(os.path.join(current_app.config["UPLOAD_FOLDER"], filename))
